-- Theme Engine schema.
--
-- Introduces the reusable, versioned, schema-driven theme domain used by the
-- native storefront. Themes are platform-controlled definitions; Theme Versions
-- are immutable after publication; Theme Installations bind a Store to a specific
-- Theme Version (one active installation per store, enforced by PostgreSQL); and
-- Theme Configurations keep separate draft/published JSONB with revision counters
-- for deterministic, revision-based cache keys.
--
-- Installations are append-only history: switching themes deactivates the current
-- row and inserts a new one, so a store may accumulate many rows for the same
-- theme version over time (A -> B -> A is legal). Only the partial unique index
-- below constrains the live state.
--
-- UUIDs are generated by the application (uuid.NewString), matching the rest of
-- the schema, so no gen_random_uuid() default is used here.

CREATE TABLE themes (
    id          UUID PRIMARY KEY,
    key         TEXT NOT NULL UNIQUE,
    name        TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    type        TEXT NOT NULL CHECK (type IN ('free', 'premium')),
    status      TEXT NOT NULL CHECK (status IN ('draft', 'active', 'deprecated', 'disabled')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE theme_versions (
    id                        UUID PRIMARY KEY,
    theme_id                  UUID NOT NULL REFERENCES themes (id) ON DELETE RESTRICT,
    version                   TEXT NOT NULL,
    status                    TEXT NOT NULL CHECK (status IN ('draft', 'published', 'deprecated')),
    configuration_schema      JSONB NOT NULL,
    default_configuration     JSONB NOT NULL,
    component_registry_version TEXT NOT NULL DEFAULT '',
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at              TIMESTAMPTZ,
    deprecated_at            TIMESTAMPTZ,
    UNIQUE (theme_id, version),
    -- Referenced by the composite FK on theme_installations so a store can never
    -- be bound to a version that belongs to a different theme.
    UNIQUE (theme_id, id)
);

CREATE TABLE theme_installations (
    id               UUID PRIMARY KEY,
    store_id         UUID NOT NULL REFERENCES stores (id) ON DELETE RESTRICT,
    theme_id         UUID NOT NULL REFERENCES themes (id) ON DELETE RESTRICT,
    theme_version_id UUID NOT NULL REFERENCES theme_versions (id) ON DELETE RESTRICT,
    status           TEXT NOT NULL CHECK (status IN ('active', 'inactive')),
    installed_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Composite integrity: the installed version must belong to the installed
    -- theme. Without this, theme_id and theme_version_id could disagree.
    FOREIGN KEY (theme_id, theme_version_id)
        REFERENCES theme_versions (theme_id, id) ON DELETE RESTRICT
);

-- Enforce a single active installation per store. A store may have many inactive
-- (historical/switched) installations, but only one may be active at a time.
CREATE UNIQUE INDEX theme_installations_one_active_per_store
    ON theme_installations (store_id) WHERE status = 'active';

CREATE TABLE theme_configurations (
    id                 UUID PRIMARY KEY,
    installation_id    UUID NOT NULL REFERENCES theme_installations (id) ON DELETE RESTRICT,
    draft_config       JSONB NOT NULL,
    published_config   JSONB NOT NULL,
    draft_revision     INTEGER NOT NULL DEFAULT 0 CHECK (draft_revision >= 0),
    published_revision INTEGER NOT NULL DEFAULT 0 CHECK (published_revision >= 0),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at       TIMESTAMPTZ,
    UNIQUE (installation_id)
);

CREATE TABLE theme_assets (
    id               UUID PRIMARY KEY,
    theme_version_id UUID NOT NULL REFERENCES theme_versions (id) ON DELETE RESTRICT,
    asset_type       TEXT NOT NULL,
    uri              TEXT NOT NULL,
    integrity        TEXT NOT NULL DEFAULT '',
    metadata         JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX theme_versions_theme_id_idx ON theme_versions (theme_id);
CREATE INDEX theme_installations_store_id_idx ON theme_installations (store_id);
CREATE INDEX theme_configurations_installation_id_idx ON theme_configurations (installation_id);
CREATE INDEX theme_assets_theme_version_id_idx ON theme_assets (theme_version_id);
