package openapi

import "dropshipping/internal/platformapi"

type CollectionResponse[T any] = platformapi.CollectionResponse[T]
type StatusResponse = platformapi.StatusResponse
type CountResponse = platformapi.CountResponse
type MarketsResponse = platformapi.MarketsResponse
type SupplierProfileResponse = platformapi.SupplierProfileResponse
type SellerProfileResponse = platformapi.SellerProfileResponse
type ProductCreateResponse = platformapi.ProductCreateResponse
type InventoryAdjustmentResponse = platformapi.InventoryAdjustmentResponse
type SupplierProfileUpdateRequest = platformapi.SupplierProfileUpdateRequest
type SellerProfileUpdateRequest = platformapi.SellerProfileUpdateRequest
type SupplierLocationCreateRequest = platformapi.SupplierLocationCreateRequest
type SupplierProductTranslationRequest = platformapi.SupplierProductTranslationRequest
type SupplierProductCreateRequest = platformapi.SupplierProductCreateRequest
type SupplierProductCategoriesRequest = platformapi.SupplierProductCategoriesRequest
type SupplierOfferCreateRequest = platformapi.SupplierOfferCreateRequest
type InventorySnapshotCreateRequest = platformapi.InventorySnapshotCreateRequest
type InventoryAdjustmentRequest = platformapi.InventoryAdjustmentRequest
type SellerStoreCreateRequest = platformapi.SellerStoreCreateRequest
type SellerListingImportRequest = platformapi.SellerListingImportRequest
type SellerListingPriceRequest = platformapi.SellerListingPriceRequest
type StatusUpdateRequest = platformapi.StatusUpdateRequest
